-- 创建浏览历史表
CREATE TABLE IF NOT EXISTS public.event_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- 钱包地址或用户ID
    event_id BIGINT NOT NULL REFERENCES public.predictions(id) ON DELETE CASCADE,
    viewed_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, event_id) -- 每个用户对每个事件只保留一条最新记录
);

-- 创建索引以优化查询
CREATE INDEX IF NOT EXISTS idx_event_views_user_id ON public.event_views(user_id);
CREATE INDEX IF NOT EXISTS idx_event_views_viewed_at ON public.event_views(viewed_at DESC);

-- 启用 RLS
ALTER TABLE public.event_views ENABLE ROW LEVEL SECURITY;

-- 允许所有用户插入（记录浏览）
CREATE POLICY "event_views_insert_all" ON public.event_views FOR INSERT WITH CHECK (true);

-- 允许用户更新自己的记录（更新浏览时间）
CREATE POLICY "event_views_update_own" ON public.event_views FOR UPDATE USING (true) WITH CHECK (true);

-- 允许用户查询自己的浏览记录
CREATE POLICY "event_views_select_own" ON public.event_views FOR SELECT USING (true);

-- 添加注释
COMMENT ON TABLE public.event_views IS '用户浏览预测事件的历史记录';
