-- Phase 1 & 2: User Profile Extensions (Proxy Wallet & Embedded Wallet)
-- These columns might have been added to create-user-profiles.sql but need to be applied to existing tables.

ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS is_reviewer BOOLEAN DEFAULT FALSE;
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS proxy_wallet_address TEXT;
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS proxy_wallet_type TEXT;
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS embedded_wallet_provider TEXT;
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS embedded_wallet_address TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_profiles_proxy_wallet_address_unique
  ON public.user_profiles (proxy_wallet_address)
  WHERE proxy_wallet_address IS NOT NULL AND proxy_wallet_address <> '';

-- Phase 5: Identity & Audit Tables (Auth Sessions & Devices)
-- Referenced in apps/web/src/app/api/auth/audit/route.ts

CREATE TABLE IF NOT EXISTS public.user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_address TEXT NOT NULL,
  session_id TEXT NOT NULL UNIQUE,
  chain_id INT NULL,
  auth_method TEXT NULL,
  ip_prefix TEXT NULL,
  user_agent TEXT NULL,
  device_id TEXT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ DEFAULT NOW(),
  revoked_at TIMESTAMPTZ NULL
);
CREATE INDEX IF NOT EXISTS user_sessions_wallet_address_idx ON public.user_sessions (wallet_address);
CREATE INDEX IF NOT EXISTS user_sessions_last_seen_at_idx ON public.user_sessions (last_seen_at DESC);
ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.user_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_address TEXT NOT NULL,
  device_id TEXT NOT NULL,
  first_seen_at TIMESTAMPTZ DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ DEFAULT NOW(),
  verified_at TIMESTAMPTZ NULL,
  last_ip_prefix TEXT NULL,
  last_user_agent TEXT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(wallet_address, device_id)
);
CREATE INDEX IF NOT EXISTS user_devices_wallet_address_idx ON public.user_devices (wallet_address);
CREATE INDEX IF NOT EXISTS user_devices_last_seen_at_idx ON public.user_devices (last_seen_at DESC);
ALTER TABLE public.user_devices ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.login_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_address TEXT NOT NULL,
  method TEXT NOT NULL,
  ip_prefix TEXT NULL,
  user_agent TEXT NULL,
  device_id TEXT NULL,
  risk_score INT NULL,
  risk_reason TEXT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS login_audit_events_wallet_address_idx ON public.login_audit_events (wallet_address);
CREATE INDEX IF NOT EXISTS login_audit_events_created_at_idx ON public.login_audit_events (created_at DESC);
ALTER TABLE public.login_audit_events ENABLE ROW LEVEL SECURITY;

-- Ensure columns exist if tables were already created (idempotency for Phase 5 updates)
ALTER TABLE public.user_sessions ADD COLUMN IF NOT EXISTS device_id TEXT NULL;
ALTER TABLE public.login_audit_events ADD COLUMN IF NOT EXISTS device_id TEXT NULL;
ALTER TABLE public.login_audit_events ADD COLUMN IF NOT EXISTS risk_score INT NULL;
ALTER TABLE public.login_audit_events ADD COLUMN IF NOT EXISTS risk_reason TEXT NULL;

-- Phase 4: Analytics Events
-- Referenced in apps/web/src/lib/serverUtils.ts

CREATE TABLE IF NOT EXISTS public.analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL,
  event_properties JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS analytics_events_name_idx ON public.analytics_events (event_name);
CREATE INDEX IF NOT EXISTS analytics_events_created_at_idx ON public.analytics_events (created_at DESC);
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
